### ISSUE TITLE
print-local-keys.py - USER_EMAIL_ILLEGAL

### ISSUE THREAD

**Issue by Saesh123** [FlagX/ha-ledvance-tuya-resync-localkey#16]
Hi, 
i get this answer, when I call 'python3 print-local-keys.py' via terminal on my Mac.

`Error! Code: USER_EMAIL_ILLEGAL, message: Invalid email address, result: {'t': 1690490204481, 'success': False, 'errorCode': 'USER_EMAIL_ILLEGAL', 'status': 'error', 'errorMsg': 'Invalid email address'}
Unexpected error: Invalid result, check logs`
......
`in _api
    raise ValueError("You need to login first.")
ValueError: You need to login first.
`

I have already changed the account name, changed the password, adjusted the country code and so on. 
What am I missing?

- Python 3.11.4
- pip 23.2.1

**Comment by FlagX** [comment]
Sorry for the late response. Are you sure have have typed in a correct email?
