### ISSUE TITLE
new device -> print-local-keys.py

### ISSUE THREAD

**Issue by Milo-PRT** [FlagX/ha-ledvance-tuya-resync-localkey#2]
I think this is more of a question than an issue.

when i query the local keys, i get the following message:

_➜  python3 print-local-keys.py
Traceback (most recent call last):
  File "/config/print-local-keys.py", line 1, in <module>
    from pyscript_modules.tuya.api import TuyaAPI
  File "/config/pyscript_modules/tuya/__init__.py", line 2, in <module>
    from .api import TuyaAPI
  File "/config/pyscript_modules/tuya/api.py", line 6, in <module>
    from Crypto.Util.number import bytes_to_long, long_to_bytes
ModuleNotFoundError: No module named 'Crypto'_

My goal is to be able to read out the devID and the local key of a newly connected plug in the Ledvance app so that these can be entered in LocalTuya.

Am I doing something wrong here?

**Comment by FlagX** [comment]
You need to install pycryptodome

```pip install pycryptodome```

I will add this to the readme.

**Comment by Milo-PRT** [comment]
perfect!
After a "python print-local-keys.py" all devices with their corresponding keys and IDs are now visible.
Many thanks for the great work - TOP!
