### ISSUE TITLE
[Question]Grouping

### ISSUE THREAD

**Issue by Snauzz** [FlagX/ha-ledvance-tuya-resync-localkey#21]
Hello,
First thing, thanks for this, worked like a charm.

Is there anyway to "group" lights like in the app, to controll and change color, brightness?
Open for idéas.

BR

**Comment by FlagX** [comment]
@Snauzz, you can create groups in the app but I am not sure if you could control them with localtuya.
Anyway, I grouped my lights with scenes in home assistant. This works perfectly and I can recommend this approach.
