### ISSUE TITLE
Does this still work after the latest Tuya API changes?

### ISSUE THREAD

**Issue by JAudi23** [FlagX/ha-ledvance-tuya-resync-localkey#25]
I had this set up on a previous instance of HA and it worked great.  I'm trying to set it up on my latest instance, and it seems to be installed correctly, but am getting an error as shown in the below screenshot.

![image](https://github.com/FlagX/ha-ledvance-tuya-resync-localkey/assets/107599616/73d448e2-05e1-43c9-a286-4d36c82d2afa)

Any guidance on fixing this?

**Comment by FlagX** [comment]
@JAudi23 still works for me. This looks like the same issue as here: https://github.com/FlagX/ha-ledvance-tuya-resync-localkey/issues/1 maybe some of the constants need to be adjusted.

**Comment by JAudi23** [comment]
Thanks, I used that method you linked previously at it worked great before, but I've lost the files i used (with the constants), let me review my codes again and see where I went wrong.
