### ISSUE TITLE
Ledvance Smart+ Plug: strange local_key format

### ISSUE THREAD

**Issue by paulius2k** [FlagX/ha-ledvance-tuya-resync-localkey#34]
I reset and re-registered one of my [Ledvance Smart Plugs](https://www.ledvance.com/consumer/products/smart-home/smart-home-products-with-wifi-technology/smart-home-components/plug-with-smart-socket-to-control-non-smart-devices-with-wifi-technology--pairable-with-remote-controller-c6482).

Running `print-local-keys.py` gives me a list of all my plugs, but the newly registered plug's `local_key` is in a different format, e.g. (redacted): `*6aK!:DZUnQ+i_w(`.  It seems like it is somehow encoded?

The plugs I have registered long time ago have the `local_key` in the format: `a974fuu7x5k923s7`.

I cannot connect to my newly registered plug from HA, whereas untouched old plugs integrate fine.

Are there any additional steps I need to take to get the correct `local_key`?

**Comment by FlagX** [comment]
Have you tried to reset the plug? This should generate a new local key, maybe there is a special character which messes things up somewhere.

**Comment by paulius2k** [comment]
I reset the plug (holding power button for 10 secs), again got the `local_key` in a "strange" format, but this time I managed to integrate it in to HA.  
It must have been my router issue all of these times, as I see that pings are not getting through to the device sometimes. Closing this issue as seems not to be a software issue.
