### ISSUE TITLE
where to type

### ISSUE THREAD

**Issue by humanBeer** [FlagX/ha-ledvance-tuya-resync-localkey#5]
I dont get it.
Where am i supposed to put 
  pip install pycryptodome
  python print-local-keys.py
?

**Comment by mesoblaste** [comment]
I have the same question.
I tried typing 

```
pip install pycryptodome
python print-local-keys.py
```

in the Home Assistant command line but I got this in return : 

```
[core-ssh ~]$ pip install pycryptodome 
python print-local-keys.py 
bash: pip: command not found 
bash: python: command not found
```

What should I do?
